# Generated by Django 4.1.4 on 2023-01-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='personal_email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
