# Generated by Django 4.1.4 on 2023-01-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_graduated_current_profile_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduated',
            name='Date_of_Join',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='Date_of_UniGrad',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='Salary',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
