# Generated by Django 4.1.4 on 2023-01-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_document_alter_drive_semester'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='documents',
        ),
    ]
