# Generated by Django 4.1.6 on 2023-02-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_document_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='unplaced',
            name='Eligible',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AlterField(
            model_name='internship',
            name='semester',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=15),
        ),
        migrations.AlterField(
            model_name='placements',
            name='semester',
            field=models.CharField(choices=[('8', '8'), ('7', '7')], max_length=15),
        ),
    ]
