# Generated by Django 4.1.6 on 2023-02-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_unplaced_eligible_alter_internship_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='Type',
            field=models.CharField(choices=[(' On Campus', ' On Campus'), (' Off Campus', ' Off Campus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='placements',
            name='Category',
            field=models.CharField(choices=[(' Open Dream', ' Open Dream'), (' Dream', ' Dream')], max_length=20),
        ),
    ]
